apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CloudNativePG Operator
# Deploy this once per cluster, not per environment

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.22/releases/cnpg-1.22.0.yaml
